FROM node:17.3.0-alpine as build

ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/src ./src
COPY frontend/public ./public

RUN npm run build

FROM nginx:1.15.6-alpine

COPY docker/frontend.conf \
    /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
